Code reorganized with packages.
tatevikb/person-and-friends pull request #2
Opened 2020-07-29 18:03 UTC by tatevikb

Added packages.

2020-07-31 14:21 UTC, nsimonyan requested changes

2020-07-31 14:21 UTC, nsimonyan commented on person/src/homeworks/person/core/model/BasePerson.java
> +import homeworks.person.core.service.PersonAction;
@tatevikb jan model should be pure object , and actions are services , so you need service package where you will store interfaces for action and in service package impl package to do exact implementations

2020-07-31 14:55 UTC, tatevikb commented on person/src/homeworks/person/core/model/BasePerson.java
> +import homeworks.person.core.service.PersonAction;
Ok, @nsimonyan jan, I moved action interfaces from impl to service package.

2020-08-02 08:51 UTC, tatevikb commented
With packages.

2020-08-02 08:51 UTC, merged